name: taccuino_fisarmonica
description: "Taccuino Fisarmonica — un blocco note musicale per annotare assoli di fisarmonica."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  flutter_soloud: ^3.1.0
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
